### ISSUE TITLE
A user can edit a snippet

### ISSUE THREAD

**Issue by AndreasFurster** [AndreasFurster/snippet-clipboard-app#1]
# Acceptance Criteria 

- [ ] All fields are preloaded with the snippet's previous fields
- [ ] There is error handling for when the editing snippet cannot be loaded
- [ ] Required fields:
  - [ ] Type (eg: text/code/image)
  - [ ] Snippet content
- [ ] Optional fields:
  - [ ] Keywords (for search)
- [ ] There is error handling for all required fields
- [ ] There is error handling for when the snippet is deleted while editing

# Tasks

- [ ] Get snippet by id from url
- [ ] Load full snippet 
- [ ] Load all snippet data into edit form
- [ ] Create GraphQL endpoint to update a snippet
- [ ] Dispatch 'update snippet' action when a user clicked the save button
- [ ] Query API to update the editing snippet
- [ ] Dispatch 'cancel edit snippet' action when a user clicked the cancel button
