### ISSUE TITLE
The user can visit an index of all snippets

### ISSUE THREAD

**Issue by AndreasFurster** [AndreasFurster/snippet-clipboard-app#11]
# Dependencies
- [#3 A user can delete a snippet](https://github.com/AndreasFurster/snippet-clipboard-app/issues/3)

# Acceptance Criteria 

- [ ] When a user presses the add button a new snippet is created
- [ ] There is error handling when the snippet cannot be created
- [ ] After creation the user is forwarded to the edit page. All rules of #1 apply

# Tasks

- [ ] Create GraphQL endpoint to create new snippet
- [ ] Dispatch 'add snippet' action on Add button click
- [ ] Query API to create a new snippet
- [ ] Forward to the edit page with the id of the newly created snippet
