### ISSUE TITLE
A user can add text as snippet content

### ISSUE THREAD

**Issue by AndreasFurster** [AndreasFurster/snippet-clipboard-app#7]
# Dependencies
- [#2 A user can create a new snippet](https://github.com/AndreasFurster/snippet-clipboard-app/issues/2)
- [#1 A user can edit a snippet](https://github.com/AndreasFurster/snippet-clipboard-app/issues/1)

# Acceptance Criteria 

- [x] The user can select the snippet type to be text
- [x] The user can click the snippet to copy the text

# Tasks

- [x] Add support for text in GraphQL endpoint
